#\u041E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u043E \u0438\u0437 \u043F\u0440\u0438\u043B\u043E\u0436\u0435\u043D\u0438\u044F
#Fri Sep 25 18:00:26 MSK 2026
db.active=mssql
db.mssql.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.mssql.password=6482
db.mssql.url=jdbc\:sqlserver\://localhost\:1433;databaseName\=warehouse;encrypt\=true;trustServerCertificate\=true;
db.mssql.user=sa
db.postgres.driver=org.postgresql.Driver
db.postgres.password=6482
db.postgres.url=jdbc\:postgresql\://localhost\:5432/postgres
db.postgres.user=postgres
